name: prestamo_mc_2_0
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.3
  firebase_auth: ^4.10.1
  get_cli: ^1.8.4
  get_storage: ^2.1.1
  responsive_sizer: ^3.2.0
  flutter_localization: ^0.1.14
  flutter_localizations:
    sdk: flutter
  flutter_login: ^4.2.1
  reactive_date_time_picker: ^3.0.0
  intl: ^0.18.0
  flutter_local_notifications: ^16.1.0
  timezone: ^0.9.2

 

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
